### ISSUE TITLE
Using a scrollable div instead of the browser viewport

### ISSUE THREAD

**Issue by yagoferrer** [shahata/angular-viewport-watch#7]

**Comment by poshest** [comment]
+1 

Shame this was closed. The requirement seems clear to me from the title, despite that @yagoferrer didn't provide any further detail.

**Comment by yagoferrer** [comment]
Hey @poshest, I was able to get it to work and I created a demo to show to my team. https://github.com/yagoferrer/ng-smart-scroll 

Use npm install / npm start to see it running. 

Let me know if that works for you :)

**Comment by poshest** [comment]
Hey @yagoferrer, awesome! Thanks very much.  I'll try it out and let you know how it goes. :)
